### PR TITLE
use templatefile function instead of data resource

### LINKED ISSUE #20: Not working on apple M1
## Describe the Bug
This module is using provider `hashicorp/template` https://registry.terraform.io/providers/hashicorp/template/latest/docs#deprecation which is deprecated
Provider `hashicorp/template` does not work on `darwin_arm64` platform.

Please migrate `data` sources to use new functions that are compatible with `darwin_arm64` (as described in provider deprecation notice)

## Expected Behavior
Module should work on darwin_arm64.

## Steps to Reproduce

1. Have darwin_arm64 platform
2. `terraform init`
3. See error 
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may
│ have different platforms supported.
```

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

- latest module version
- platform `darwin_arm64`
```
terraform -v
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### PR DESCRIPTION
**Pull request by moperacz**
## what
instead of using deprecated (and not supported on new Macs) hashicorp/template provider use `templatefile` function

Provider hashicorp/template does not work on darwin_arm64 platform.

## references
closes #20

### CODE REVIEW

**Comment by b1n9s** [comment]
had the issue in #20, would be great if this can be merged

**Comment by Gowiem** [comment]
@moperacz can you pull in the changes from the `master` branch into your PR? That will fix our tests and get this moving along. Thanks!

**Comment by moperacz** [comment]
@Gowiem done 😉

**Review by Gowiem — APPROVED** [review]

**Comment by ivanmartos** [comment]
Please why is the `hashicorp/template` still listed in versions file after this change?

https://github.com/cloudposse/terraform-aws-iam-user/issues/20#issuecomment-1195270118

**Comment by b1n9s** [comment]
> Please why is the `hashicorp/template` still listed in versions file after this change?
> 
> [#20 (comment)](https://github.com/cloudposse/terraform-aws-iam-user/issues/20#issuecomment-1195270118)

could be from the state file, should be removed after you run a `terraform apply`

**Comment by ivanmartos** [comment]
it is still listed in `required_providers` in versions.tf of this module
https://github.com/cloudposse/terraform-aws-iam-user/blob/master/versions.tf
If it is not required anymore can it be removed please?

**Comment by Gowiem** [comment]
@ivanmartos you're correct -- we missed that. Can you put up a PR and request a review from me? I'll review and merge ASAP.

**Comment by Gowiem** [comment]
@ivanmartos @b1n9s @moperacz -- @mehowthe was gracious enough to put up a PR to address removing the provider block. That was just merged and has been released as https://github.com/cloudposse/terraform-aws-iam-user/releases/tag/0.8.4

**Pull request merged**
