### PR TITLE
Update version for terraform-null-label module

### PR DESCRIPTION
**Pull request by chess-seventh**
This PR updates the version to 0.16 (as used in the terraform-aws-iam-system-user module), updates the terraform syntax and add types to all variables for consistency.

### CODE REVIEW

**Comment by chess-seventh** [comment]
Hello @maximmi!

Thanks for the input, here is my first try to add (at least the tests),
I am going a little blindly here, but if I understood properly what has
been done in the PR you've shared, I (think) shouldn't be too wrong?

Let me know if there is more stuff to add/change. I'll be happy to amend
the other 2 PRs I have.

Thanks!

**Comment by chess-seventh** [comment]
Hello @maximmi!

Thanks for the input, here is my first try to add (at least the tests),
I am going a little blindly here, but if I understood properly what has
been done in the PR you've shared, I (think) shouldn't be too wrong?

Let me know if there is more stuff to add/change. I'll be happy to amend
the other 2 PRs I have.

Thanks!

**Comment by ivanmartos** [comment]
any update pls?

**Comment by ivanmartos** [comment]
there were some issues in original fork, I fixed them
https://github.com/crowdhouse/terraform-aws-iam-user

**Pull request closed without merging**
